In [2]:
import pandas as pd
import numpy as np

In [3]:
animaux_df = pd.read_csv("fr_animaux.csv", sep=",")
cereales_df = pd.read_csv("fr_céréales.csv", sep=",")
population_df = pd.read_csv("fr_population.csv", sep=",")
sousalimentation_df = pd.read_csv("fr_sousalimentation.csv", sep=",")
vegetaux_df = pd.read_csv("fr_vegetaux.csv", sep=",")

In [3]:
population_df[population_df['Zone'].str.contains('Chine')][['Code zone', 'Zone', 'Valeur']]
#affichage des zones "Chine"

    Code zone                       Zone   Valeur
33        351                      Chine  1416667
34         96   Chine - RAS de Hong-Kong     7204
35        128       Chine - RAS de Macao      566
36         41        Chine, continentale  1385567
37        214  Chine, Taiwan Province de    23330

In [4]:
population_df = population_df[population_df['Code zone'] != 351] 
animaux_df = animaux_df[animaux_df['Code zone'] != 351]
cereales_df = cereales_df[cereales_df['Code zone'] != 351] 
sousalimentation_df = sousalimentation_df[sousalimentation_df['Code zone'] != 351] 
vegetaux_df = vegetaux_df[vegetaux_df['Code zone'] != 351] 
#suppression de la ligne Chine qui est un aggrégat de la Chine continentale et de ses territoires indépendants

In [5]:
population_mondiale = population_df['Valeur'].sum() * 1000 
population_mondiale_miard = population_df['Valeur'].sum() / 1000000
print('La population mondiale en 2013 était de ' + str(population_mondiale) + ", soit " + str(population_mondiale_miard) + " milliards.")

La population mondiale en 2013 était de 6997326000, soit 6.997326 milliards.

In [6]:
#Selon l'ONU, la population mondiale était de 6.956824 en 2010, et de 7379797 en 2015, soit +6.08%. 
#En 2013 elle aurait donc dû être supérieure.
#source : https://fr.wikipedia.org/wiki/Population_mondiale#%C3%89volution_depuis_1950

nbre_pays_fao = len(population_df)
print('La FAO recense ' + str(nbre_pays_fao) + ' pays')

La FAO recense 174 pays

Or les nations unies recensent 193 pays. La population mondiale est donc sous évaluée par la FAO.
source : https://fr.wikipedia.org/wiki/Liste_des_%C3%89tats_membres_de_l%27Organisation_des_Nations_unies

"Question 2 : Identifiez ces redondances, en donnant votre réponse sous forme de formule mathématique"

In [8]:
#Variation = disponibilité intérieure + exportations - production - importation
#Pertes = disponibilité intérieure - semences - autres utilisations - nourriture - aliments - traitement
#Disponibilité intérieure = variation - exportations + production + importations
#Disponibilité intérieure = pertes + semences + autres utilisations + nourriture + aliments pour animaux + traitement

"Illustrez cette équation avec l'exemple du blé en France."

In [9]:
#création d'un dataframe Blé en France
bleFr = vegetaux_df.loc[(vegetaux_df['Zone'] == 'France') & (vegetaux_df['Produit'] == 'Blé')]
bleFr.reset_index(drop=True)

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5511,Production,2511,Blé,2013,2013,Milliers de tonnes,38614.00,S,Données standardisées
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5611,Importations - Quantité,2511,Blé,2013,2013,Milliers de tonnes,2055.00,S,Données standardisées
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5072,Variation de stock,2511,Blé,2013,2013,Milliers de tonnes,1131.00,S,Données standardisées
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5911,Exportations - Quantité,2511,Blé,2013,2013,Milliers de tonnes,21502.00,S,Données standardisées
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5301,Disponibilité intérieure,2511,Blé,2013,2013,Milliers de tonnes,20298.00,S,Données standardisées
5,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5521,Aliments pour animaux,2511,Blé,2013,2013,Milliers de tonnes,7822.00,S,Données standardisées
6,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5527,Semences,2511,Blé,2013,2013,Milliers de tonnes,748.00,S,Données standardisées
7,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5123,Pertes,2511,Blé,2013,2013,Milliers de tonnes,358.00,S,Données standardisées
8,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5131,Traitement,2511,Blé,2013,2013,Milliers de tonnes,1575.00,S,Données standardisées
9,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5154,Autres utilisations (non alimentaire),2511,Blé,2013,2013,Milliers de tonnes,2824.00,S,Données standardisées
10,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,5142,Nourriture,2511,Blé,2013,2013,Milliers de tonnes,6971.00,S,Données standardisées
11,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,645,Disponibilité alimentaire en quantité (kg/pers...,2511,Blé,2013,2013,kg,108.43,Fc,Donnée calculée
12,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,664,Disponibilité alimentaire (Kcal/personne/jour),2511,Blé,2013,2013,Kcal/personne/jour,811.00,Fc,Donnée calculée
13,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,674,Disponibilité de protéines en quantité (g/pers...,2511,Blé,2013,2013,g/personne/jour,25.99,Fc,Donnée calculée
14,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,68,France,684,Disponibilité de matière grasse en quantité (g...,2511,Blé,2013,2013,g/personne/jour,4.20,Fc,Donnée calculée

In [10]:
bleFr.iloc[4]['Valeur']
#Disponibilité intérieure selon la ligne correspondante du dataframe

20298.0

In [11]:
prod=int(bleFr[bleFr["Élément"]=="Production"].Valeur)
importa=int(bleFr[bleFr["Élément"]=="Importations - Quantité"].Valeur)
export=int(bleFr[bleFr["Élément"]=="Exportations - Quantité"].Valeur)
variation=int(bleFr[bleFr["Élément"]=="Variation de stock"].Valeur)
dispo=int(bleFr[bleFr["Élément"]=="Disponibilité intérieure"].Valeur)
semences=int(bleFr[bleFr["Élément"]=="Semences"].Valeur)
pertes=int(bleFr[bleFr["Élément"]=="Pertes"].Valeur)
nourriture=int(bleFr[bleFr["Élément"]=="Nourriture"].Valeur)
aliments=int(bleFr[bleFr["Élément"]=="Aliments pour animaux"].Valeur)
traitement=int(bleFr[bleFr["Élément"]=="Traitement"].Valeur)
autre=int(bleFr[bleFr["Élément"]=="Autres utilisations (non alimentaire)"].Valeur)

In [12]:
print(variation== dispo+ export- prod- importa)
dispo+ export- prod- importa

True

1131

In [13]:
print(pertes==dispo-semences-autre-nourriture-aliments-traitement)
dispo-semences-autre-nourriture-aliments-traitement

True

358

In [14]:
print(dispo==variation-export+prod+importa)
variation-export+prod+importa

True

20298

In [15]:
print(dispo==pertes+semences+autre+nourriture+aliments+traitement)
pertes+semences+autre+nourriture+aliments+traitement

True

20298

Question 3 : Calculez (pour chaque pays et chaque produit) la disponibilité alimentaire en kcal puis en kg de protéines.

In [16]:
#Création de deux dataframes animaux et végétaux, et jointure sous bilan_alim
bilan_alim_anim = animaux_df
bilan_alim_anim['origine'] = 'animal'
bilan_alim_veg = vegetaux_df
bilan_alim_veg['origine'] = 'vegetal'
bilan_alim = bilan_alim_anim.append(bilan_alim_veg)

#Passage des colonnes en ligne
bilan_alim = pd.pivot_table(bilan_alim, index=['Code zone', 'Zone', 'Code Produit', 'Produit', 'origine'], columns = 'Élément', values = 'Valeur', aggfunc=np.sum).reset_index()
bilan_alim.columns.name = None
bilan_alim = bilan_alim.rename(columns = {'Zone' : 'pays', 
                                          'Code zone' : 'code_pays', 
                                          'Produit' : 'produit', 
                                          'Code Produit' : 'code_produit', 
                                          'Année' : 'annee',
                                          'Aliments pour animaux' : 'alim_animaux',
                                          'Autres utilisations (non alimentaire)' : 'autres',
                                          'Disponibilité alimentaire (Kcal/personne/jour)' : 'dispo_kcal_p_j',
                                          'Disponibilité alimentaire en quantité (kg/personne/an)' : 'dispo_kg_p',
                                          'Disponibilité de matière grasse en quantité (g/personne/jour)' : 'dispo_mat_g_p_j',
                                          'Disponibilité de protéines en quantité (g/personne/jour)' : 'dispo_prot_g_p_j',
                                          'Disponibilité intérieure': 'dispo_int',
                                          'Exportations - Quantité' : 'exports',
                                          'Importations - Quantité' : 'imports',
                                          'Nourriture' : 'nourriture',
                                          'Pertes' : 'pertes',
                                          'Production' : 'prod',
                                          'Semences' : 'semences',
                                          'Traitement' : 'traitement',
                                          'Variation de stock' : 'var_stock'})

population_df = population_df.rename(columns = {'Zone' : 'pays', 
                                          'Code zone' : 'code_pays',
                                          'Produit' : 'produit',
                                          'Unité' : 'unité',
                                          'Valeur' : 'population',
                                          'Année' : 'annee'})

In [17]:
#jointure entre le dataframe population_df et le bilan_alim, et suppression de colonnes inutiles
bilan_alim = pd.merge(bilan_alim, population_df, on =['pays', 'code_pays'])
bilan_alim.drop(['Symbole', 'Description du Symbole', 'Code Domaine', 'Domaine', 'Code année', 'Élément','Code Élément', "Code Produit", "annee"], axis=1)

,code_pays,pays,code_produit,produit_x,origine,alim_animaux,autres,dispo_kcal_p_j,dispo_kg_p,dispo_mat_g_p_j,...,imports,nourriture,pertes,prod,semences,traitement,var_stock,produit_y,unité,population
0,1,Arménie,2511,Blé,vegetal,93.0,0.0,1024.0,130.60,3.60,...,361.0,389.0,32.0,312.0,30.0,10.0,-118.0,Population,1000 personnes,2977
1,1,Arménie,2513,Orge,vegetal,137.0,26.0,0.0,0.00,0.00,...,9.0,0.0,15.0,189.0,14.0,7.0,0.0,Population,1000 personnes,2977
2,1,Arménie,2514,Maïs,vegetal,96.0,NaN,0.0,0.03,NaN,...,82.0,0.0,7.0,21.0,0.0,NaN,NaN,Population,1000 personnes,2977
3,1,Arménie,2515,Seigle,vegetal,1.0,NaN,1.0,0.12,0.00,...,0.0,0.0,0.0,1.0,0.0,NaN,0.0,Population,1000 personnes,2977
4,1,Arménie,2516,Avoine,vegetal,4.0,NaN,2.0,0.37,0.03,...,1.0,1.0,0.0,5.0,0.0,NaN,NaN,Population,1000 personnes,2977
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15600,276,Soudan,2763,Poissons Pelagiques,animal,NaN,0.0,0.0,0.00,0.00,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,Population,1000 personnes,37964
15601,276,Soudan,2764,"Poissons Marins, Autres",animal,NaN,0.0,0.0,0.13,0.01,...,NaN,5.0,NaN,5.0,NaN,NaN,NaN,Population,1000 personnes,37964
15602,276,Soudan,2805,Riz (Eq Blanchi),vegetal,NaN,NaN,14.0,1.27,0.05,...,33.0,48.0,NaN,17.0,1.0,NaN,0.0,Population,1000 personnes,37964
15603,276,Soudan,2848,Lait - Excl Beurre,animal,NaN,0.0,315.0,155.20,20.01,...,232.0,5892.0,NaN,5660.0,NaN,0.0,NaN,Population,1000 personnes,37964
15604,276,Soudan,2899,Miscellanees,vegetal,NaN,NaN,7.0,NaN,0.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Population,1000 personnes,37964

In [18]:
#Colonne disponibilité alimentaire en kcal total pour chaque pays et chaque produit
bilan_alim['dispo_alim_kcal'] = bilan_alim['dispo_kcal_p_j']* (bilan_alim['population']*1000)* 365

In [19]:
#Colonne disponibilité alimentaire en protéines pour chaque pays et chaque produit
bilan_alim['dispo_alim_prot'] = (bilan_alim['dispo_prot_g_p_j'] / 1000) * (bilan_alim['population']*1000) * 365

In [20]:
bilan_alim_q3 = bilan_alim[['pays', 'produit_x', 'dispo_alim_kcal', 'dispo_alim_prot']]
bilan_alim_q3

          pays                produit_x  dispo_alim_kcal  dispo_alim_prot
0      Arménie                      Blé     1.112684e+12     3.316318e+07
1      Arménie                     Orge     0.000000e+00     0.000000e+00
2      Arménie                     Maïs     0.000000e+00     1.086605e+04
3      Arménie                   Seigle     1.086605e+09     2.173210e+04
4      Arménie                   Avoine     2.173210e+09     9.779445e+04
...        ...                      ...              ...              ...
15600   Soudan      Poissons Pelagiques     0.000000e+00     0.000000e+00
15601   Soudan  Poissons Marins, Autres     0.000000e+00     5.542744e+05
15602   Soudan         Riz (Eq Blanchi)     1.939960e+11     3.879921e+06
15603   Soudan       Lait - Excl Beurre     4.364911e+12     2.182455e+08
15604   Soudan             Miscellanees     9.699802e+10     2.036958e+07

[15605 rows x 4 columns]

Question 4 : A partir de ces dernières informations, et à partir du poids de la disponibilité alimentaire (pour chaque pays et chaque produit), calculez pour chaque produit le ratio "énergie/poids", que vous donnerez en kcal/kg.

In [21]:
#Colonne ratio énergie/poids
bilan_alim['ratio_energie'] = bilan_alim['dispo_alim_kcal']/(bilan_alim['dispo_kg_p']*1000*bilan_alim['population'])

In [22]:
bilan_alim_q4 = bilan_alim[['pays', 'produit_x', 'dispo_alim_kcal', 'dispo_alim_prot','ratio_energie']]
bilan_alim_q4

,pays,produit_x,dispo_alim_kcal,dispo_alim_prot,ratio_energie
0,Arménie,Blé,1.112684e+12,3.316318e+07,2861.868300
1,Arménie,Orge,0.000000e+00,0.000000e+00,NaN
2,Arménie,Maïs,0.000000e+00,1.086605e+04,0.000000
3,Arménie,Seigle,1.086605e+09,2.173210e+04,3041.666667
4,Arménie,Avoine,2.173210e+09,9.779445e+04,1972.972973
...,...,...,...,...,...
15600,Soudan,Poissons Pelagiques,0.000000e+00,0.000000e+00,NaN
15601,Soudan,"Poissons Marins, Autres",0.000000e+00,5.542744e+05,0.000000
15602,Soudan,Riz (Eq Blanchi),1.939960e+11,3.879921e+06,4023.622047
15603,Soudan,Lait - Excl Beurre,4.364911e+12,2.182455e+08,740.818299
15604,Soudan,Miscellanees,9.699802e+10,2.036958e+07,NaN

En suivant la même méthodologie, calculez également le pourcentage de protéines de chaque produit (pour chaque pays). 
Ce pourcentage est obtenu en calculant le ratio "poids de protéines/poids total" (attention aux unités utilisées). 
Vous pouvez vérifier la cohérence de votre calcul en comparant ce ratio aux données disponibles sur internet, par exemple en cherchant la teneur en protéines de l'avoine.

In [23]:
#Colonne pourcentage de protéines
bilan_alim['proteines (%)'] = (bilan_alim['dispo_alim_prot'] /(bilan_alim['dispo_kg_p']*1000*bilan_alim['population'])) * 100

In [24]:
bilan_alim_q4b = bilan_alim[['pays', 'produit_x', 'dispo_alim_kcal', 'dispo_alim_prot','ratio_energie','proteines (%)']]
bilan_alim_q4b

,pays,produit_x,dispo_alim_kcal,dispo_alim_prot,ratio_energie,proteines (%)
0,Arménie,Blé,1.112684e+12,3.316318e+07,2861.868300,8.529709
1,Arménie,Orge,0.000000e+00,0.000000e+00,NaN,NaN
2,Arménie,Maïs,0.000000e+00,1.086605e+04,0.000000,12.166667
3,Arménie,Seigle,1.086605e+09,2.173210e+04,3041.666667,6.083333
4,Arménie,Avoine,2.173210e+09,9.779445e+04,1972.972973,8.878378
...,...,...,...,...,...,...
15600,Soudan,Poissons Pelagiques,0.000000e+00,0.000000e+00,NaN,NaN
15601,Soudan,"Poissons Marins, Autres",0.000000e+00,5.542744e+05,0.000000,11.230769
15602,Soudan,Riz (Eq Blanchi),1.939960e+11,3.879921e+06,4023.622047,8.047244
15603,Soudan,Lait - Excl Beurre,4.364911e+12,2.182455e+08,740.818299,3.704091
15604,Soudan,Miscellanees,9.699802e+10,2.036958e+07,NaN,NaN

Question 5 : Citez 5 aliments parmi les 20 aliments les plus caloriques, en utilisant le ratio énergie/poids.
Étonnamment, il arrive que ce ratio soit différent en fonction du pays. Il faudra donc réaliser pour chaque aliment une moyenne sur les différents pays. Vous créerez donc une nouvelle table grâce à une agrégation. Attention à bien retirer les valeurs égales à 0 afin de ne pas fausser le calcul de la moyenne.

In [25]:
dispo_moy_energie = bilan_alim.groupby(bilan_alim['produit_x']).agg('mean')
dispo_moy_energie = dispo_moy_energie.replace([-np.inf, np.inf], np.nan)
dispo_moy_energie = dispo_moy_energie.sort_values('ratio_energie', ascending = False)
dispo_moy_energie = dispo_moy_energie[['ratio_energie', 'proteines (%)']].reset_index()
print(dispo_moy_energie.iloc[0:20])

                  produit_x  ratio_energie  proteines (%)
0            Huile de Palme    8791.217534       0.391267
1             Huile de Soja    8625.483876       0.201601
2       Huile de Son de Riz    8497.969939       0.688679
3   Huile de Colza&Moutarde    8368.869607       0.239452
4        Huile de Tournesol    8305.568299       0.131633
5   Huil Plantes Oleif Autr    8246.215771       0.571416
6    Huile Graines de Coton    8177.340910       0.178576
7             Huile de Coco    8097.752477       0.435161
8        Huile de Palmistes    7885.602997       0.268712
9    Huile de Germe de Maïs    7827.167158       0.190793
10         Huile d'Arachide    7803.918649       0.126736
11            Huile d'Olive    7774.263485       0.000000
12   Graisses Animales Crue    7579.278844       1.352675
13          Huile de Sésame    7482.722820       0.000000
14       Huiles de Poissons    7133.945055       0.000000
15             Beurre, Ghee    6946.278887       0.633141
16   Arachides Decortiquees    5466.324644      24.790816
17                   Sésame    5010.932143      17.828134
18            Feve de Cacao    4343.034036       7.174112
19         Riz (Eq Blanchi)    3640.609092       7.001246

Citez 5 aliments parmi les 20 aliments les plus riches en protéines.

In [26]:
dispo_moy_prot = bilan_alim.groupby(['produit_x']).agg('mean')
dispo_moy_prot = dispo_moy_prot.replace([-np.inf, np.inf], np.nan)
dispo_moy_prot = dispo_moy_prot.sort_values('proteines (%)', ascending = False)
dispo_moy_prot = dispo_moy_prot[['ratio_energie', 'proteines (%)']].reset_index()
print(dispo_moy_prot.iloc[0:20])

                   produit_x  ratio_energie  proteines (%)
0                       Soja    1748.819646      25.338211
1     Arachides Decortiquees    5466.324644      24.790816
2                       Pois    3106.951940      22.108112
3        Légumineuses Autres    3170.465864      22.025876
4                   Haricots    3256.453914      21.719055
5                     Sésame    5010.932143      17.828134
6           Abats Comestible    1125.965304      17.630901
7              Viande, Autre    1086.200200      17.410158
8   Plantes Oleiferes, Autre    2631.827466      16.693495
9      Aliments pour enfants    3050.469022      14.872622
10          Viande de Bovins    1689.213495      14.461108
11              Cephalopodes     376.592794      14.057333
12    Viande d'Ovins/Caprins    1933.424399      13.736265
13       Viande de Volailles    1301.168956      12.620016
14       Poissons Pelagiques     888.304389      12.129966
15                   Piments    2514.499721      11.337096
16    Graines Colza/Moutarde            NaN      10.950000
17   Poissons Marins, Autres     593.706597      10.942450
18            Épices, Autres    3106.064527      10.744898
19                     Oeufs    1364.817772      10.696134

In [27]:
#Les résultats semblent cohérents avec les chiffres trouvés sur internet de 16,96% de protéines pour les graines de sésames 
#et 11,96% pour les oeufs.
#sources : https://www.lanutrition.fr/oeuf-frais ; https://www.lanutrition.fr/graine-de-sesame-grillee

Question 6 : Calculez, pour les produits végétaux uniquement, la disponibilité intérieure mondiale exprimée en kcal.

In [28]:
#Création d'un dataframe 'bilan_alim_veg' en ne conservant que les données d'origine végétale 
#et en supprimant les infinis et les nan
bilan_alim_veg = bilan_alim.loc[bilan_alim['origine'] == 'vegetal']
bilan_alim_veg = bilan_alim_veg.replace([-np.inf, np.inf], np.nan)

#Nombre de calories totales à partir de la disponibilité intérieure mondiale
bilan_alim_veg['dispo_int_kcal'] = (bilan_alim_veg['dispo_int'] * 1000000) * bilan_alim_veg['ratio_energie']
dispo_int_veg_kcal = round(bilan_alim_veg['dispo_int_kcal'].sum(skipna=True),2)
print('Disponibilité intérieure issue des produits d\'origine végétale : ' + str(dispo_int_veg_kcal) + ' kcal.')

Disponibilité intérieure issue des produits d'origine végétale : 1.2166421524173388e+16 kcal.

Question 7 : Combien d'humains pourraient être nourris si toute la disponibilité intérieure mondiale de produits végétaux était utilisée pour de la nourriture ? Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.

In [29]:
#Les recommandations d'apport en énergie des adultes étant de 2 400 à 2 600 calories par jour pour un homme
#et de 1 800 à 2200 calories par jour pour les femmes, on peut considérer 2200 comme apport moyen recommandé pour un adulte
#source: https://www.vidal.fr/sante/nutrition/equilibre-alimentaire-adulte/recommandations-nutritionnelles-adulte.html
nbre_humains_kcal = bilan_alim_veg['dispo_int_kcal'].sum(skipna=True) / (2200 * 365)
prcent_humains_kcal = (nbre_humains_kcal /(population_df['population'].sum(skipna=True)*1000))* 100
print('Pourcentage d\'humains nourris avec les calories de la disponibilité intérieure : ' + str(prcent_humains_kcal) + " %")

bilan_alim_veg['dispo_int_prot'] = (bilan_alim_veg['dispo_int'] * 1000000) * (bilan_alim_veg['proteines (%)']/100)
dispo_int_veg_prot = round(bilan_alim_veg['dispo_int_prot'].sum(skipna=True),2)
print('Disponibilité intérieure issue des produits d\'origine végétale : ' + str(dispo_int_veg_prot) + ' kg de protéines.')

#Les recommandations d'apport en protéines sont en g de protéines /kg/jour. Vidal recommande ainsi 44g pour une femme de 
#55kg sédentaire. On peut considérer que la consommation moyenne en protéines nécessaire à un être humain 
#est de 50 g par jour.
nbre_humains_proteine = dispo_int_veg_prot / (50 * 1000 * 365)
pourcentage_humains_proteine = (nbre_humains_proteine / population_df['population'].sum(skipna=True)*1000) * 100
print('Pourcentage d\'humains nourris avec les protéines de la disponibilité intérieure : '  
     + str(pourcentage_humains_proteine) +  ' %')

Pourcentage d'humains nourris avec les calories de la disponibilité intérieure : 216.52856917358062 %
Disponibilité intérieure issue des produits d'origine végétale : 291995825800.39 kg de protéines.
Pourcentage d'humains nourris avec les protéines de la disponibilité intérieure : 228.65550750006074 %

Question 8 : Combien d'humains pourraient être nourris si toute la disponibilité alimentaire en produits végétaux, la nourriture végétale destinée aux animaux et les pertes de produits végétaux étaient utilisés pour de la nourriture ? 
Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.

In [30]:
bilan_alim_veg['potentiel_kg'] = (bilan_alim_veg['nourriture'] + bilan_alim_veg['pertes'] + bilan_alim_veg['alim_animaux']) * 1000000
bilan_alim_veg['potentiel_kcal'] = bilan_alim_veg['potentiel_kg'] * bilan_alim_veg['ratio_energie']
potentiel_kcal_veg = bilan_alim_veg['potentiel_kcal'].sum(skipna=True)
print('Disponibilité alimentaire (nourriture, pertes et aliments pour animaux) : ' + str(potentiel_kcal_veg) + ' kcal.')

nb_humains_kcal_veg = potentiel_kcal_veg / (2000 * 365)
prcent_humains_kcal_veg =  (nb_humains_kcal_veg / (population_df['population'].sum(skipna=True)*1000)) * 100
print('Pourcentage d\'humains nourris avec la nourriture, les pertes et l\'alimentation animale : ' 
     + str(prcent_humains_kcal_veg) + " %")

bilan_alim_veg['potentiel_prot_kcal'] = bilan_alim_veg['potentiel_kg'] * (bilan_alim_veg['proteines (%)'] / 100)
potentiel_prot_veg = bilan_alim_veg['potentiel_prot_kcal'].sum(skipna=True)
print('Disponibilité alimentaire (nourriture, pertes et aliments pour animaux) : ' + str(potentiel_prot_veg) + ' kg de protéines.')

nb_humains_prot_veg = bilan_alim_veg['potentiel_prot_kcal'].sum(skipna=True) / ((50 / 1000) * 365)
prcent_humains_proteine_veg = (nb_humains_prot_veg / (population_df['population'].sum(skipna=True)*1000))*100
print('Pourcentage d\'humains nourris avec la nourriture, les pertes et l\'alimentation animale : ' 
     + str(prcent_humains_proteine_veg) + " %")

Disponibilité alimentaire (nourriture, pertes et aliments pour animaux) : 6103854708181490.0 kcal.
Pourcentage d'humains nourris avec la nourriture, les pertes et l'alimentation animale : 119.49485854636568 %
Disponibilité alimentaire (nourriture, pertes et aliments pour animaux) : 161047080637.75153 kg de protéines.
Pourcentage d'humains nourris avec la nourriture, les pertes et l'alimentation animale : 126.11242593516243 %

Question 9 : Combien d'humains pourraient être nourris avec la disponibilité alimentaire mondiale ? 
Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.

In [31]:
bilan_alim['nourriture_kcal'] = (bilan_alim['nourriture']*1000000) * bilan_alim['ratio_energie']
bilan_alim = bilan_alim.replace([-np.inf, np.inf], np.nan)
nourriture_tot = bilan_alim['nourriture_kcal'].sum(skipna=True)
print('Nourriture d\'origine animale et végétale : ' + str(nourriture_tot) + ' kcal.')
nb_humain_kcal_nourriture = bilan_alim['nourriture_kcal'].sum(skipna=True) / (2000 * 365)
prcent_humains_kcal_nourriture =  (nb_humain_kcal_nourriture / (population_df['population'].sum(skipna=True)*1000)) * 100
print('Pourcentage d\'humains nourris avec la nourriture d\'origine animale et végétale : ' 
     + str(prcent_humains_kcal_nourriture) + " %")


bilan_alim['nourriture_prot'] = bilan_alim['nourriture'] * (bilan_alim['proteines (%)']/100)
nourriture_prot_tot = bilan_alim['nourriture_prot'].sum(skipna=True)
print('Nourriture d\'origine animale et végétale : ' + str(nourriture_prot_tot) + ' kg de protéines.')
nb_humains_proteine_nourriture = bilan_alim['nourriture_prot'].sum(skipna=True) / ((50 / 1000)* 365)
prcent_humains_proteine_nourriture = (nb_humains_proteine_nourriture/ population_df['population'].sum(skipna=True)*1000)  * 100
print('Pourcentage d\'humains nourris avec la nourriture d\'origine animale et végétale : ' 
     + str(prcent_humains_proteine_nourriture) + " %")

Nourriture d'origine animale et végétale : 7357936865086520.0 kcal.
Pourcentage d'humains nourris avec la nourriture d'origine animale et végétale : 144.04596225203272 %
Nourriture d'origine animale et végétale : 207153.4766853036 kg de protéines.
Pourcentage d'humains nourris avec la nourriture d'origine animale et végétale : 162.21733037464818 %

Question 10 : A partir des données téléchargées qui concernent la sous-nutrition, répondez à cette question : 
Quelle proportion de la population mondiale est considérée comme étant en sous-nutrition ?

In [32]:
sous_nutrition = sousalimentation_df
sous_nutrition = sous_nutrition.loc[sous_nutrition['Année'] == '2012-2014']
sous_nutrition = sous_nutrition.replace('<0.1', 0.1)
sous_nutrition = sous_nutrition.drop(columns= ['Code Domaine', 'Domaine', 'Code Élément', 'Élément', 'Code Produit', 'Produit', 'Code année', 'Année', 'Unité', 'Symbole', 'Description du Symbole', 'Note'])
population_df = population_df.drop(columns= ['Code Domaine', 'Domaine', 'Code Élément', 'Élément', 'Code Produit', 'Code année', 'Symbole', 'Description du Symbole'])
sous_nutrition = sous_nutrition.rename(columns = {'Code zone' : 'code_pays',
                                                  'Zone' : 'pays',
                                                  'Valeur' : 'nb_habitants'})
sous_nutrition = pd.merge(sous_nutrition, population_df, on=['pays', 'code_pays'])
sous_nutrition = sous_nutrition.astype({'nb_habitants' : 'float'})

prcent_ss_nutrition = round(((sous_nutrition['nb_habitants'].sum(skipna=True)*1000)/(sous_nutrition['population'].sum(skipna=True))*100),2)
print('Nombre de personnes sous-alimentés : ' + str(sous_nutrition['nb_habitants'].sum(skipna=True)) + ' milliers.')
print('Pourcentage de personnes sous-alimentés : ' + str(prcent_ss_nutrition) + '%')

Nombre de personnes sous-alimentés : 746.0 milliers.
Pourcentage de personnes sous-alimentés : 10.66%

Établissez la liste des produits (ainsi que leur code) considéré comme des céréales selon la FAO.
Repérez dans vos données les informations concernant les céréales (par exemple en créant une colonne de type booléen nommée "is_cereal").

In [33]:
cereales_consommable = cereales_df[['Produit','Code Produit']]
cereales_consommable = cereales_consommable.drop_duplicates()
cereales_consommable = cereales_consommable.rename(columns = {'Produit' : 'produit_x',
                                                              'Code Produit' : 'code_produit'})
cereales_consommable

           produit_x  code_produit
0                Blé          2511
1   Riz (Eq Blanchi)          2805
2               Orge          2513
3               Maïs          2514
4             Millet          2517
9             Seigle          2515
10            Avoine          2516
12            Sorgho          2518
13  Céréales, Autres          2520

Question 11 : En ne prenant en compte que les céréales destinées à l'alimentation (humaine et animale), quelle proportion (en termes de poids) est destinée à l'alimentation animale ?

In [34]:
cereales_alim = pd.merge(cereales_consommable,  bilan_alim_veg, on = 'produit_x')
cereales_tot_alim = cereales_alim['nourriture'].sum(skipna=True)
cereales_tot_anim = cereales_alim['alim_animaux'].sum(skipna=True)
print("Quantité de céréales destinée à l'alimentation totale : " + str(cereales_tot_alim) + " milliers de tonnes.")
print("Quantité de céréales nécessaires à l'alimentation animale : " + str(cereales_tot_anim) + " milliers de tonnes.")
print("Quantité de céréales restantes après suppression de l'alimentation animale : " + str(abs(cereales_tot_alim - cereales_tot_anim)) + " milliers de tonnes.")
ratio = cereales_tot_anim/(cereales_tot_alim + cereales_tot_anim) * 100
ratio = round(ratio, 2)
print("Ratio alimentation animale/alimentation totale : " + str(ratio) + " %")

Quantité de céréales destinée à l'alimentation totale : 1029010.0 milliers de tonnes.
Quantité de céréales nécessaires à l'alimentation animale : 873535.0 milliers de tonnes.
Quantité de céréales restantes après suppression de l'alimentation animale : 155475.0 milliers de tonnes.
Ratio alimentation animale/alimentation totale : 45.91 %

Sélectionnez parmi les données des bilans alimentaires les informations relatives aux pays dans lesquels la FAO recense des personnes en sous-nutrition.
Repérez les 15 produits les plus exportés par ce groupe de pays.

In [35]:
sous_nutrition = sous_nutrition.sort_values('nb_habitants', ascending = False)
sous_nutrition = sous_nutrition.dropna()
bilan_alim_ss_nutrition = pd.merge(bilan_alim, sous_nutrition, on=['code_pays', 'pays', 'annee', 'population'])
bilan_alim_ss_nutrition = bilan_alim_ss_nutrition.groupby(['produit_x']).agg('sum')
bilan_alim_ss_nutrition = bilan_alim_ss_nutrition.sort_values('exports', ascending=False)
bilan_alim_ss_nutrition = bilan_alim_ss_nutrition.head(15)
bilan_alim_ss_nutrition = bilan_alim_ss_nutrition.reset_index()
print(bilan_alim_ss_nutrition['produit_x'])

0          Huile de Palme
1                    Maïs
2                  Manioc
3        Riz (Eq Blanchi)
4           Sucre Eq Brut
5                     Blé
6         Légumes, Autres
7                 Bananes
8      Lait - Excl Beurre
9          Fruits, Autres
10                   Soja
11    Poissons Pelagiques
12                Tomates
13                 Pommes
14    Oranges, Mandarines
Name: produit_x, dtype: object

Parmi les données des bilans alimentaires au niveau mondial, sélectionnez les 200 plus grandes importations de ces produits
(1 importation = une quantité d'un produit donné importée par un pays donné)

In [36]:
produit_export_ss_alim = pd.DataFrame(bilan_alim_ss_nutrition['produit_x'])
bilan_alim_imports = pd.merge(bilan_alim, produit_export_ss_alim, on = ['produit_x'])
bilan_alim_imports = bilan_alim_imports.sort_values('imports', ascending=False)
bilan_alim_imports = bilan_alim_imports.iloc[0:200]
print(bilan_alim_imports[['code_pays', 'pays', 'produit_x', 'imports']])

      code_pays                 pays           produit_x  imports
714          41  Chine, continentale                Soja  63381.0
375          41  Chine, continentale              Manioc  29046.0
251         110                Japon                Maïs  14403.0
41           59               Égypte                 Blé  10331.0
257         117  République de Corée                Maïs   8755.0
...         ...                  ...                 ...      ...
2328        131             Malaisie    Riz (Eq Blanchi)   1079.0
1271        106               Italie     Légumes, Autres   1061.0
2572        237             Viet Nam  Lait - Excl Beurre   1041.0
122         173              Pologne                 Blé   1037.0
196          33               Canada                Maïs   1035.0

[200 rows x 4 columns]

Groupez ces importations par produit, afin d'avoir une table contenant 1 ligne pour chacun des 15 produits.

In [37]:
bilan_alim_imports = bilan_alim_imports.groupby(['produit_x']).sum()
bilan_alim_imports = bilan_alim_imports.sort_values('imports', ascending = False)
bilan_alim_imports = bilan_alim_imports.reset_index()
print(bilan_alim_imports[['produit_x', 'imports']])

              produit_x   imports
0                   Blé  147576.0
1                  Maïs  102451.0
2                  Soja   93455.0
3    Lait - Excl Beurre   88418.0
4                Manioc   34655.0
5         Sucre Eq Brut   34208.0
6        Huile de Palme   29747.0
7       Légumes, Autres   28177.0
8   Oranges, Mandarines   22945.0
9        Fruits, Autres   15714.0
10     Riz (Eq Blanchi)   13990.0
11  Poissons Pelagiques   13445.0
12              Bananes    9663.0
13               Pommes    8518.0
14              Tomates    7143.0

Ensuite, calculez pour chaque produit les 2 quantités suivantes :
le ratio entre la quantité destinés aux "Autres utilisations" (Other uses) et la disponibilité intérieure.
le ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine)

In [38]:
bilan_alim_imports['ratio(autres/dispo_int)'] = bilan_alim_imports['autres']/bilan_alim_imports['dispo_int']
bilan_alim_imports['ratio(alim_anim/nourriture)'] = bilan_alim_imports['alim_animaux']/bilan_alim_imports['nourriture']
bilan_alim_imports = bilan_alim_imports.replace([-np.inf, np.inf], np.nan)
print(bilan_alim_imports[['produit_x', 'ratio(autres/dispo_int)', 'ratio(alim_anim/nourriture)']])

              produit_x  ratio(autres/dispo_int)  ratio(alim_anim/nourriture)
0                   Blé                 0.032963                     0.326172
1                  Maïs                 0.259771                     7.204925
2                  Soja                 0.003284                     1.825566
3    Lait - Excl Beurre                 0.036006                     0.090600
4                Manioc                 0.302335                     1.648358
5         Sucre Eq Brut                 0.038188                     0.000000
6        Huile de Palme                 0.724803                     0.000000
7       Légumes, Autres                 0.000000                     0.052568
8   Oranges, Mandarines                 0.000051                     0.000000
9        Fruits, Autres                 0.000000                     0.000000
10     Riz (Eq Blanchi)                 0.018664                     0.102937
11  Poissons Pelagiques                 0.000000                     3.087630
12              Bananes                 0.000000                     0.000000
13               Pommes                 0.000000                     0.000000
14              Tomates                 0.000000                     0.000000

Question 12 : Donnez les 3 produits qui ont la plus grande valeur pour chacun des 2 ratios (vous aurez donc 6 produits à citer)

In [39]:
bilan_alim_imports = bilan_alim_imports.sort_values('ratio(autres/dispo_int)', ascending = False)
print(bilan_alim_imports['produit_x'].iloc[0:3])

6    Huile de Palme
4            Manioc
1              Maïs
Name: produit_x, dtype: object

In [40]:
bilan_alim_imports = bilan_alim_imports.sort_values('ratio(alim_anim/nourriture)', ascending = False)
print(bilan_alim_imports['produit_x'].iloc[0:3])

1                    Maïs
11    Poissons Pelagiques
2                    Soja
Name: produit_x, dtype: object

Question 13 : Combien de tonnes de céréales pourraient être libérées si les USA diminuaient leur production de produits animaux de 10% ?

In [41]:
cereales_usa = bilan_alim.loc[bilan_alim['pays'] == 'États-Unis d\'Amérique']
cereales_usa = pd.merge(cereales_consommable, cereales_usa, on = ['produit_x', 'code_produit'])
cereales_tot_usa = cereales_usa['alim_animaux'].sum(skipna=True)
print('La production totale de céréales des USA pour l\'alimentation animale est de ' + str(cereales_tot_usa) + ' milliers de tonnes par an.')

prcent_tot_usa = cereales_tot_usa * 0.01
print('Si les USA diminuaient de 10% leur production,  ' + str(prcent_tot_usa) + ' milliers de tonnes de céréales seraient libérés par an.')

La production totale de céréales des USA pour l'alimentation animale est de 140096.0 milliers de tonnes par an.
Si les USA diminuaient de 10% leur production,  1400.96 milliers de tonnes de céréales seraient libérés par an.

Question 14 : En Thaïlande, quelle proportion de manioc est exportée ? Quelle est la proportion de personnes en sous-nutrition?

In [42]:
thailande = bilan_alim.loc[(bilan_alim['pays'] == 'Thaïlande') & (bilan_alim['produit_x'] == 'Manioc')]
export_manioc_thailande = thailande['exports'].sum(skipna=True)
print('Proportion de manioc exportée par la Thaïlande : ' + str(export_manioc_thailande) + ' milliers de tonnes.')
thailande = pd.merge(thailande, sous_nutrition, on = ['pays', 'code_pays', 'annee', 'population'])
prcent_ss_nutr_thailande = round(((thailande['nb_habitants'].sum(skipna=True)* 1000) / thailande['population'].sum(skipna=True)) * 100, 2)
print('Pourcentage de thaïlandais sous-alimentés : ' + str(prcent_ss_nutr_thailande) +'%')

Proportion de manioc exportée par la Thaïlande : 25214.0 milliers de tonnes.
Pourcentage de thaïlandais sous-alimentés : 8.36%

In [43]:
thailande['kcal_exports'] = (thailande['exports'] * 1000000) * bilan_alim['ratio_energie']
manioc_kcal = thailande['kcal_exports'].sum(skipna=True)
nb_humain_manioc = round(manioc_kcal/(2000 * 365),2)
pourcentage_hab_manioc = round((nb_humain_manioc/67011000) * 100,2)
print('Cette quantité de manioc pourrait nourrir ' + str(nb_humain_manioc) + ' thaïlandais, soit ' + str(pourcentage_hab_manioc) + ' % de la population thaïlandaise.')

Cette quantité de manioc pourrait nourrir 98848147.01 thaïlandais, soit 147.51 % de la population thaïlandaise.